// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lexxys.T1.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ObjectTemplate : ObjectTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/*\r\n\tServer: ");
            
            #line 8 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Lexxys.Config.GetValue<Lexxys.ConnectionStringInfo>("database.connection").Server));
            
            #line default
            #line hidden
            this.Write("\r\n\tFile: ");
            
            #line 9 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.PublicName));
            
            #line default
            #line hidden
            this.Write(".cs (v ");
            
            #line 9 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(System.Reflection.Assembly.GetExecutingAssembly().GetName().Version));
            
            #line default
            #line hidden
            this.Write(" at ");
            
            #line 9 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.UtcNow.ToString("u")));
            
            #line default
            #line hidden
            this.Write(")\r\n*/\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing Assertion = System" +
                    ".Diagnostics.Contracts.Contract;\r\nusing System.Linq;\r\nusing System.Threading.Tas" +
                    "ks;\r\n\r\nusing Lexxys;\r\n");
            
            #line 18 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

foreach (var u in Project.Using)
{
	if (String.IsNullOrEmpty(u))
		continue;
	var v = u.Trim();
	if (!v.EndsWith(";"))
		v += ";";

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 27 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(v));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

}
var objNamespace = Project.Namespace ?? "Entities";

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 33 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tusing Data;\r\n\r\n");
            
            #line 37 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	var cls = table.Class;
	string className = table.PublicName;
	string recordName = className + "Record";
	ColumnInfo keyColumn = table.KeyFields.Count == 1 ? table.KeyFields[0]: ColumnInfo.DefaultIdKey;
	TableInfo view = table.View;

            
            #line default
            #line hidden
            this.Write("\tpublic class ");
            
            #line 44 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(": IDump\r\n\t{\r\n\t\t//private static readonly Logger Log => __log ??= new Logger(\"");
            
            #line 46 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objNamespace.Substring(objNamespace.LastIndexOf('.') + 1) + "." + className));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t//private static Logger __log;\r\n\r\n\t\tprivate readonly ");
            
            #line 49 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(" _record;\r\n\r\n\t\tpublic ");
            
            #line 51 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(): this(new ");
            
            #line 51 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write("())\r\n\t\t{\r\n\t\t}\r\n\r\n\t\tprivate ");
            
            #line 55 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 55 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(" record)\r\n\t\t{\r\n\t\t\t_record = record ?? throw new ArgumentNullException(nameof(reco" +
                    "rd));\r\n\t\t}\r\n\r\n\t\t#region Auto Properties\r\n\r\n");
            
            #line 62 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	foreach (var field in view.Fields)
	{
		if (field.IsExcluded)
			continue;

		if (!field.IsReadonly && !field.IsProtected && !field.IsPrivate && !field.IsPrimaryKey && !field.IsIdentity && !field.IsComputed && field.InitializationExpression == null)
		{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 70 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CsFieldType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 70 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write(" { get => _record.");
            
            #line 70 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write("; set => _record.");
            
            #line 70 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 70 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CsType == "string" ? "value.TrimToNull()":
				field.CsType == "byte[]" ? "value == null || value.Length == 0 ? null: value": "value"));
            
            #line default
            #line hidden
            this.Write("; }\r\n\r\n");
            
            #line 75 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 79 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CsFieldType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 79 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write(" => _record.");
            
            #line 79 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 81 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write(@"		public bool IsModified => _record.IsRecordModified;

		public bool IsNew => _record.IsRecordNew;

		#endregion

		public ValidationResults Validation { get; set; }

		public bool TryUpdate()
		{
			if (!IsModified)
				return SetValidated();
");
            
            #line 97 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	if (view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DateDeleted"))
	{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (DateDeleted != null && IsNew)\r\n\t\t\t\treturn true;\r\n");
            
            #line 103 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write(@"			if (!Validate().Success)
				return false;
			try
			{
				_record.SaveChanges();
				return true;
			}
			catch (Exception flaw)
			{
				flaw.Add(""this"", this.Dump());
				throw;
			}
		}

		public async Task<bool> TryUpdateAsync()
		{
			if (!IsModified)
				return SetValidated();
");
            
            #line 124 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	if (view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DateDeleted"))
	{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (DateDeleted != null && IsNew)\r\n\t\t\t\treturn true;\r\n");
            
            #line 130 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write(@"			if (!Validate().Success)
				return false;
			try
			{
				await _record.SaveChangesAsync();
				return true;
			}
			catch (Exception flaw)
			{
				flaw.Add(""this"", this.Dump());
				throw;
			}
		}

		private bool SetValidated()
		{
			Validation = ValidationResults.Empty;
			return true;
		}

		public ValidationResults Validate()
		{
			Assertion.Ensures(Assertion.Result<ValidationResults>() != null);

			var results = _record.Validate();
			return Validation = results;
		}

		public void Update()
		{
			if (!TryUpdate())
				Validation.Invariant(""Update"", () => this.Dump());
		}

		public async Task UpdateAsync()
		{
			if (!await TryUpdateAsync())
				Validation.Invariant(""UpdateAsync"", () => this.Dump());
		}
");
            
            #line 172 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	foreach (var method in table.Loads)
	{
		var keys = method.Fields;
		if (keys.Count == 0)
			continue;
		var methodName = method.NameByParameters("Load");

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static ");
            
            #line 181 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" Try");
            
            #line 181 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 181 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o => o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar record = ");
            
            #line 183 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 183 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 183 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\treturn record == null ? null: new ");
            
            #line 184 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(record);\r\n\t\t}\r\n\r\n\t\tpublic static async Task<");
            
            #line 187 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> Try");
            
            #line 187 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 187 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar record = await ");
            
            #line 189 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 189 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 189 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\treturn record == null ? null: new ");
            
            #line 190 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(record);\r\n\t\t}\r\n");
            
            #line 192 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var method in table.Loads)
	{
		var keys = method.Fields;
		if (keys.Count == 0)
			continue;
		var methodName = method.NameByParameters("Load");

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static ");
            
            #line 203 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 203 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 203 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 205 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n");
            
            #line 206 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			if (keys.Count == 1) {

            
            #line default
            #line hidden
            this.Write("\t\t\treturn Try");
            
            #line 209 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 209 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(") ?? throw EX.ArgumentOutOfRange(nameof(");
            
            #line 209 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 209 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 210 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\treturn Try");
            
            #line 215 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 215 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(") ?? throw EX.ArgumentOutOfRange($\"(");
            
            #line 215 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",", keys.Select(o=> "{nameof(" + Tool.NormalizeName(o.Name, NameStyle.LocalName) + ")}"))));
            
            #line default
            #line hidden
            this.Write(")\", (");
            
            #line 215 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 216 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic static async Task<");
            
            #line 221 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 221 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 221 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 223 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n");
            
            #line 224 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			if (keys.Count == 1) {

            
            #line default
            #line hidden
            this.Write("\t\t\treturn await Try");
            
            #line 227 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 227 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(") ?? throw EX.ArgumentOutOfRange(\"");
            
            #line 227 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 227 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 228 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\treturn await Try");
            
            #line 233 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 233 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(") ?? throw EX.ArgumentOutOfRange().");
            
            #line 233 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(".", keys.Select(o=> "Add(\"" + Tool.NormalizeName(o.Name, NameStyle.LocalName) + "\", " + Tool.NormalizeName(o.Name, NameStyle.LocalName) + ")"))));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 234 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 238 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	} // end of table.Load

	if (table.Loads.Any(o => o.Fields.Count == 1 && String.Equals(o.Fields[0].Name, "Id", StringComparison.OrdinalIgnoreCase)))
	{
		var method = table.Loads.First(o => o.Fields.Count == 1 && String.Equals(o.Fields[0].Name, "Id", StringComparison.OrdinalIgnoreCase));
		var key = method.Fields[0];
		var keyName = Tool.NormalizeName(key.Name, NameStyle.LocalName);
		var methodName = method.NameByParameters("Load");
		var method2Name = method.Name == "Load" ? "LoadOrCreate": method.NameByParameters("LoadOrCreate");

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static ");
            
            #line 250 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 250 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method2Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 250 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.NullabeCsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 250 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 252 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n\t\t\treturn Check.IsId(");
            
            #line 253 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write(") ? ");
            
            #line 253 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 253 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            
            #line 253 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CliType.IsValueType ? ".GetValueOrDefault()": ""));
            
            #line default
            #line hidden
            this.Write("): new ");
            
            #line 253 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t}\r\n\r\n\t\tpublic static async Task<");
            
            #line 256 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 256 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method2Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 256 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.NullabeCsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 256 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 258 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n\t\t\treturn Check.IsId(");
            
            #line 259 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write(") ? await ");
            
            #line 259 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 259 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            
            #line 259 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CliType.IsValueType ? ".GetValueOrDefault()": ""));
            
            #line default
            #line hidden
            this.Write("): new ");
            
            #line 259 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t}\r\n");
            
            #line 261 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	if (view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DateDeleted"))
	{
		var user = Project.Expression["user"];

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic void Delete()\r\n\t\t{\r\n\t\t\t_record.DateDeleted = ");
            
            #line 271 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Project.Expression["timestamp"]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 272 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		if (user == null)
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!IsNew)\r\n\t\t\t\tUpdate();\r\n");
            
            #line 278 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (IsNew)\r\n\t\t\t\t_record.DeletedBy = ");
            
            #line 284 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\telse\r\n\t\t\t\tUpdate();\r\n");
            
            #line 287 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic async Task DeleteAsync()\r\n\t\t{\r\n\t\t\t_record.DateDeleted = ");
            
            #line 294 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Project.Expression["timestamp"]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 295 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		if (user == null)
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!IsNew)\r\n\t\t\t\tawait UpdateAsync();\r\n");
            
            #line 301 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (IsNew)\r\n\t\t\t\t_record.DeletedBy = ");
            
            #line 307 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\telse\r\n\t\t\t\tawait UpdateAsync();\r\n");
            
            #line 310 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 314 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var method in table.Loads)
	{
		if (method.Delete == false || !(method.Delete == true || method.Where == null))
			continue;
		var keys = method.Fields;
		if (keys.Count == 0)
			continue;

            
            #line default
            #line hidden
            this.Write("\r\n\t\t//public static bool Delete(");
            
            #line 326 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t//{\r\n\t\t//\treturn ");
            
            #line 328 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".Delete(");
            
            #line 328 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t//}\r\n\r\n\t\t//public static Task<bool> DeleteAsync(");
            
            #line 331 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t//{\r\n\t\t//\treturn ");
            
            #line 333 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".DeleteAsync(");
            
            #line 333 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t//}\r\n");
            
            #line 335 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic DumpWriter DumpContent(DumpWriter writer)\r\n\t\t{\r\n\t\t\treturn _record.Dump" +
                    "Content(writer);\r\n\t\t}\r\n\r\n\t\t#region Collect\r\n");
            
            #line 345 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	if (table.KeyFields.Count == 1) {

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 349 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> Collect(IEnumerable<int> ids, bool ordered = false)\r\n\t\t{\r\n\t\t\tAssertion.Ensures(" +
                    "Assertion.Result<IEnumerable<");
            
            #line 351 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 352 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".Collect(ids, ordered).Select(o=> new ");
            
            #line 352 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 355 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> CollectAsync(IEnumerable<int> ids, bool ordered = false)\r\n\t\t{\r\n\t\t\tAssertion.En" +
                    "sures(Assertion.Result<IEnumerable<");
            
            #line 357 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 358 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectAsync(ids, ordered)).Select(o=> new ");
            
            #line 358 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 360 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	List<string> collected = new List<string>();

	foreach (var key in table.Fields.Where(o => o.IsUnique && o != keyColumn && o.CsType == "int"))
	{
		var name = key.FieldName;
		var idName = name.Substring(0, 1).ToLowerInvariant() + name.Substring(1);
		if (name.EndsWith("Id", StringComparison.Ordinal))
			name = name.Substring(0, name.Length - 2);
		if (collected.Contains(name))
			continue;
		collected.Add(name);

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 376 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> CollectBy");
            
            #line 376 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(IEnumerable<int> ids, bool ordered = false)\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion" +
                    ".Result<IEnumerable<");
            
            #line 378 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 379 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 379 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(ids, ordered).Select(o=> new ");
            
            #line 379 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 382 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> CollectBy");
            
            #line 382 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(IEnumerable<int> ids, bool ordered = false)\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Asse" +
                    "rtion.Result<IEnumerable<");
            
            #line 384 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 385 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 385 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(ids, ordered)).Select(o=> new ");
            
            #line 385 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 387 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var key in table.Fields.Where(o => o.Reference != null && o != keyColumn && !o.IsUnique))
	{
		var name = key.FieldName;
		var idName = name.Substring(0, 1).ToLowerInvariant() + name.Substring(1);
		if (name.EndsWith("Id", StringComparison.Ordinal))
			name = name.Substring(0, name.Length - 2);
		if (collected.Contains(name))
			continue;
		collected.Add(name);

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 401 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> CollectBy");
            
            #line 401 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 401 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 401 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 403 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 404 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 404 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 404 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(").Select(o=> new ");
            
            #line 404 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 407 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> CollectBy");
            
            #line 407 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 407 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 407 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 409 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 410 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 410 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 410 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(")).Select(o=> new ");
            
            #line 410 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 412 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var method in table.Collects)
	{
		if (method.Fields.Count == 0)
			continue;
		var name = method.NameByParameters("Collect");
		if (collected.Contains(name))
			continue;
		collected.Add(name);

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 425 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 425 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 425 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeDeclaration()));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 427 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 428 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 428 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 428 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeParameters()));
            
            #line default
            #line hidden
            this.Write(").Select(o=> new ");
            
            #line 428 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 431 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 431 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 431 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeDeclaration()));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 433 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 434 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".method");
            
            #line 434 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 434 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeParameters()));
            
            #line default
            #line hidden
            this.Write(")).Select(o=> new ");
            
            #line 434 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 436 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\t#endregion\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

private global::Lexxys.T1.TableInfo _tableField;

/// <summary>
/// Access the table parameter of the template.
/// </summary>
private global::Lexxys.T1.TableInfo table
{
    get
    {
        return this._tableField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool tableValueAcquired = false;
if (this.Session.ContainsKey("table"))
{
    this._tableField = ((global::Lexxys.T1.TableInfo)(this.Session["table"]));
    tableValueAcquired = true;
}
if ((tableValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("table");
    if ((data != null))
    {
        this._tableField = ((global::Lexxys.T1.TableInfo)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ObjectTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
