// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lexxys.T1.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ObjectTemplate : ObjectTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/*\r\n\tServer: ");
            
            #line 8 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Lexxys.Config.Current.GetValue<Lexxys.ConnectionStringInfo>("database.connection").Value?.Server));
            
            #line default
            #line hidden
            this.Write("\r\n\tFile: ");
            
            #line 9 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.PublicName));
            
            #line default
            #line hidden
            this.Write(".cs (v ");
            
            #line 9 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(System.Reflection.Assembly.GetExecutingAssembly().GetName().Version));
            
            #line default
            #line hidden
            this.Write(" at ");
            
            #line 9 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.UtcNow.ToString("u")));
            
            #line default
            #line hidden
            this.Write(")\r\n*/\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing Assertion = System" +
                    ".Diagnostics.Contracts.Contract;\r\nusing System.Linq;\r\nusing System.Threading.Tas" +
                    "ks;\r\n\r\nusing Lexxys;\r\n");
            
            #line 18 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

var dcDeclare = $"{Project.Expression.DataContextType} dc = null";

foreach (var u in Project.Using)
{
	if (String.IsNullOrEmpty(u))
		continue;
	var v = u.Trim();
	if (!v.EndsWith(";"))
		v += ";";

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 29 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(v));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 30 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

}
var objNamespace = Project.Namespace ?? "Entities";

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 35 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tusing Data;\r\n\r\n");
            
            #line 39 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	var cls = table.Class;
	string className = table.PublicName;
	string recordName = className + "Record";
	ColumnInfo keyColumn = table.KeyFields.Count == 1 ? table.KeyFields[0]: ColumnInfo.DefaultIdKey;
	TableInfo view = table.View;

            
            #line default
            #line hidden
            this.Write("\tpublic class ");
            
            #line 46 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(": IDump\r\n\t{\r\n\t\t//private static readonly Logger Log => __log ??= new Logger(\"");
            
            #line 48 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objNamespace.Substring(objNamespace.LastIndexOf('.') + 1) + "." + className));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t//private static Logger __log;\r\n\r\n\t\tprivate readonly ");
            
            #line 51 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(" _record;\r\n\r\n\t\tpublic ");
            
            #line 53 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(): this(new ");
            
            #line 53 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write("())\r\n\t\t{\r\n\t\t}\r\n\r\n\t\tprivate ");
            
            #line 57 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 57 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(" record)\r\n\t\t{\r\n\t\t\t_record = record ?? throw new ArgumentNullException(nameof(reco" +
                    "rd));\r\n\t\t}\r\n\r\n\t\t#region Auto Properties\r\n\r\n");
            
            #line 64 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	foreach (var field in view.Fields)
	{
		if (field.IsExcluded)
			continue;

		string fieldName = field.FieldName == className ? field.FieldName + "Value": field.FieldName;
		if (!field.IsReadonly && !field.IsProtected && !field.IsPrivate && !field.IsPrimaryKey && !field.IsIdentity && !field.IsComputed && field.InitializationExpression == null)
		{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 73 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CsFieldType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 73 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write(" { get => _record.");
            
            #line 73 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write("; set => _record.");
            
            #line 73 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 73 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CsType == "string" ? "value.TrimToNull()":
				field.CsType == "byte[]" ? "value == null || value.Length == 0 ? null: value": "value"));
            
            #line default
            #line hidden
            this.Write("; }\r\n\r\n");
            
            #line 78 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 82 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.CsFieldType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 82 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write(" => _record.");
            
            #line 82 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 84 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
	}
	string isPrefix = view.Fields.Any(o => o.FieldName == "IsNew" || o.FieldName == "IsModified") ? "IsObject": "Is";

            
            #line default
            #line hidden
            this.Write("\t\tpublic bool ");
            
            #line 89 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("Modified => _record.IsRecordModified;\r\n\r\n\t\tpublic bool ");
            
            #line 91 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("New => _record.IsRecordNew;\r\n\r\n\t\t#endregion\r\n\r\n\t\tpublic ValidationResults Validat" +
                    "ion { get; set; }\r\n\r\n\t\tpublic bool TryUpdate(");
            
            #line 97 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tif (!");
            
            #line 99 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("Modified)\r\n\t\t\t\treturn SetValidated();\r\n");
            
            #line 101 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	if (view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DateDeleted"))
	{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (DateDeleted != null && IsNew)\r\n\t\t\t\treturn true;\r\n");
            
            #line 107 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!Validate().Success)\r\n\t\t\t\treturn false;\r\n\t\t\ttry\r\n\t\t\t{\r\n\t\t\t\t_record.SaveCha" +
                    "nges(dc);\r\n\t\t\t\treturn true;\r\n\t\t\t}\r\n\t\t\tcatch (Exception flaw)\r\n\t\t\t{\r\n\t\t\t\tflaw.Add" +
                    "(\"this\", this.Dump());\r\n\t\t\t\tthrow;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic async Task<bool> TryUp" +
                    "dateAsync(");
            
            #line 124 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tif (!");
            
            #line 126 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("Modified)\r\n\t\t\t\treturn SetValidated();\r\n");
            
            #line 128 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	if (view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DateDeleted"))
	{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (DateDeleted != null && ");
            
            #line 132 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("New)\r\n\t\t\t\treturn true;\r\n");
            
            #line 134 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write(@"			if (!Validate().Success)
				return false;
			try
			{
				await _record.SaveChangesAsync(dc);
				return true;
			}
			catch (Exception flaw)
			{
				flaw.Add(""this"", this.Dump());
				throw;
			}
		}

		private bool SetValidated()
		{
			Validation = ValidationResults.Empty;
			return true;
		}

		public ValidationResults Validate()
		{
			Assertion.Ensures(Assertion.Result<ValidationResults>() != null);

			var results = _record.Validate();
			return Validation = results;
		}

		public void Update(");
            
            #line 165 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tif (!TryUpdate(dc))\r\n\t\t\t\tValidation.Invariant(\"Update\", () => this.Dum" +
                    "p());\r\n\t\t}\r\n\r\n\t\tpublic async Task UpdateAsync(");
            
            #line 171 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tif (!await TryUpdateAsync(dc))\r\n\t\t\t\tValidation.Invariant(\"UpdateAsync\"" +
                    ", () => this.Dump());\r\n\t\t}\r\n");
            
            #line 176 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	foreach (var method in table.Loads)
	{
		var keys = method.Fields;
		if (keys.Count == 0)
			continue;
		var methodName = method.NameByParameters("Load");

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static ");
            
            #line 185 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" Try");
            
            #line 185 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 185 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o => o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 185 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar record = ");
            
            #line 187 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 187 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 187 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc);\r\n\t\t\treturn record == null ? null: new ");
            
            #line 188 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(record);\r\n\t\t}\r\n\r\n\t\tpublic static async Task<");
            
            #line 191 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> Try");
            
            #line 191 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 191 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 191 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar record = await ");
            
            #line 193 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 193 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 193 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc);\r\n\t\t\treturn record == null ? null: new ");
            
            #line 194 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(record);\r\n\t\t}\r\n");
            
            #line 196 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var method in table.Loads)
	{
		var keys = method.Fields;
		if (keys.Count == 0)
			continue;
		var methodName = method.NameByParameters("Load");

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static ");
            
            #line 207 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 207 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 207 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 207 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 209 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n");
            
            #line 210 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			if (keys.Count == 1) {

            
            #line default
            #line hidden
            this.Write("\t\t\treturn Try");
            
            #line 213 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 213 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc) ?? throw EX.ArgumentOutOfRange(nameof(");
            
            #line 213 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 213 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 214 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\treturn Try");
            
            #line 219 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 219 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc) ?? throw EX.ArgumentOutOfRange($\"(");
            
            #line 219 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",", keys.Select(o=> "{nameof(" + Tool.NormalizeName(o.Name, NameStyle.LocalName) + ")}"))));
            
            #line default
            #line hidden
            this.Write(")\", (");
            
            #line 219 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 220 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic static async Task<");
            
            #line 225 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 225 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 225 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 225 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 227 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n");
            
            #line 228 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			if (keys.Count == 1) {

            
            #line default
            #line hidden
            this.Write("\t\t\treturn await Try");
            
            #line 231 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 231 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc) ?? throw EX.ArgumentOutOfRange(\"");
            
            #line 231 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 231 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Tool.NormalizeName(keys[0].Name, NameStyle.LocalName)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 232 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\treturn await Try");
            
            #line 237 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 237 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc) ?? throw EX.ArgumentOutOfRange().");
            
            #line 237 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(".", keys.Select(o=> "Add(\"" + Tool.NormalizeName(o.Name, NameStyle.LocalName) + "\", " + Tool.NormalizeName(o.Name, NameStyle.LocalName) + ")"))));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 238 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 242 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	} // end of table.Load

	if (table.Loads.Any(o => o.Fields.Count == 1 && String.Equals(o.Fields[0].Name, "Id", StringComparison.OrdinalIgnoreCase)))
	{
		var method = table.Loads.First(o => o.Fields.Count == 1 && String.Equals(o.Fields[0].Name, "Id", StringComparison.OrdinalIgnoreCase));
		var key = method.Fields[0];
		var keyName = Tool.NormalizeName(key.Name, NameStyle.LocalName);
		var methodName = method.NameByParameters("Load");
		var method2Name = method.Name == "Load" ? "LoadOrCreate": method.NameByParameters("LoadOrCreate");
		var checkKey = key.CsType switch
		{
			"string" => $"!String.IsNullOrEmpty({keyName})",
			"Guid" => keyName + " != Guid.Empty",
			_ => keyName + " > 0"
		};

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static ");
            
            #line 260 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 260 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method2Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 260 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.NullabeCsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 260 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 260 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 262 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n\t\t\treturn ");
            
            #line 263 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(checkKey));
            
            #line default
            #line hidden
            this.Write(" ? ");
            
            #line 263 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 263 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            
            #line 263 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CliType.IsValueType ? ".GetValueOrDefault()": ""));
            
            #line default
            #line hidden
            this.Write(", dc): new ");
            
            #line 263 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t}\r\n\r\n\t\tpublic static async Task<");
            
            #line 266 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 266 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method2Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 266 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.NullabeCsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 266 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 266 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<");
            
            #line 268 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">() != null);\r\n\t\t\treturn ");
            
            #line 269 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(checkKey));
            
            #line default
            #line hidden
            this.Write(" ? await ");
            
            #line 269 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 269 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            
            #line 269 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CliType.IsValueType ? ".GetValueOrDefault()": ""));
            
            #line default
            #line hidden
            this.Write(", dc): new ");
            
            #line 269 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t}\r\n");
            
            #line 271 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	if (view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DateDeleted"))
	{
		var user = Project.Expression["user"];

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic void Delete(");
            
            #line 279 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t_record.DateDeleted = ");
            
            #line 281 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Project.Expression["timestamp"]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 282 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		if (user == null || !view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DeletedBy"))
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!");
            
            #line 286 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("New)\r\n\t\t\t\tUpdate(dc);\r\n");
            
            #line 288 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 293 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("New)\r\n\t\t\t\t_record.DeletedBy = ");
            
            #line 294 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\telse\r\n\t\t\t\tUpdate(dc);\r\n");
            
            #line 297 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic async Task DeleteAsync(");
            
            #line 302 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t_record.DateDeleted = ");
            
            #line 304 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Project.Expression["timestamp"]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 305 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		if (user == null || !view.Fields.Any(o => !o.IsExcluded && o.FieldName == "DeletedBy"))
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!");
            
            #line 309 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("New)\r\n\t\t\t\tawait UpdateAsync(dc);\r\n");
            
            #line 311 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (");
            
            #line 316 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPrefix));
            
            #line default
            #line hidden
            this.Write("New)\r\n\t\t\t\t_record.DeletedBy = ");
            
            #line 317 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\telse\r\n\t\t\t\tawait UpdateAsync(dc);\r\n");
            
            #line 320 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 324 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var method in table.Loads)
	{
		if (method.Delete == false || !(method.Delete == true || method.Where == null))
			continue;
		var keys = method.Fields;
		if (keys.Count == 0)
			continue;

            
            #line default
            #line hidden
            this.Write("\r\n\t\t//public static bool Delete(");
            
            #line 336 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 336 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t//{\r\n\t\t//\treturn ");
            
            #line 338 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".Delete(");
            
            #line 338 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc);\r\n\t\t//}\r\n\r\n\t\t//public static Task<bool> DeleteAsync(");
            
            #line 341 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> o.CsType + " " + Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 341 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t//{\r\n\t\t//\treturn ");
            
            #line 343 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".DeleteAsync(");
            
            #line 343 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", keys.Select(o=> Tool.NormalizeName(o.Name, NameStyle.LocalName)))));
            
            #line default
            #line hidden
            this.Write(", dc);\r\n\t\t//}\r\n");
            
            #line 345 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic DumpWriter DumpContent(DumpWriter writer)\r\n\t\t{\r\n\t\t\treturn _record.Dump" +
                    "Content(writer);\r\n\t\t}\r\n\r\n\t\t#region Collect\r\n");
            
            #line 355 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	if (keyColumn.CsType == "int" && table.KeyFields.Count == 1) {

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 359 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> Collect(IEnumerable<int> ids, bool ordered = false, ");
            
            #line 359 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 361 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 362 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".Collect(ids, ordered, dc).Select(o=> new ");
            
            #line 362 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 365 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> CollectAsync(IEnumerable<int> ids, bool ordered = false, ");
            
            #line 365 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 367 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 368 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectAsync(ids, ordered, dc)).Select(o=> new ");
            
            #line 368 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 370 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	List<string> collected = new List<string>();

	foreach (var key in table.Fields.Where(o => o.IsUnique && o != keyColumn && o.CsType == "int"))
	{
		var publicName = key.GetPublicName();
		var nameItems = Strings.SplitByCapitals(publicName).Select(o => publicName.Substring(o.Index, o.Length)).ToList();
		int nameItemsCount = nameItems.Count;
		if (nameItemsCount > 1 && String.Equals(nameItems[nameItemsCount-1], "id", StringComparison.OrdinalIgnoreCase))
			--nameItemsCount;
		nameItems[nameItemsCount - 1] = Lingua.Plural(nameItems[nameItemsCount - 1]);
		var name = String.Concat(nameItems.Take(nameItemsCount));
		if (collected.Contains(name))
			continue;
		collected.Add(name);

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 389 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> CollectBy");
            
            #line 389 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(IEnumerable<int> ids, bool ordered = false, ");
            
            #line 389 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 391 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 392 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 392 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(ids, ordered, dc).Select(o=> new ");
            
            #line 392 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 395 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> CollectBy");
            
            #line 395 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(IEnumerable<int> ids, bool ordered = false, ");
            
            #line 395 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 397 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 398 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 398 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(ids, ordered, dc)).Select(o=> new ");
            
            #line 398 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 400 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var key in table.Fields.Where(o => o.Reference != null && o != keyColumn && !o.IsUnique))
	{
		var name = key.FieldName;
		var idName = name.Substring(0, 1).ToLowerInvariant() + name.Substring(1);
		if (name.EndsWith("Id", StringComparison.Ordinal))
			name = name.Substring(0, name.Length - 2);
		if (collected.Contains(name))
			continue;
		collected.Add(name);

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 414 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> CollectBy");
            
            #line 414 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 414 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 414 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 414 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 416 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 417 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 417 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 417 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(", dc).Select(o=> new ");
            
            #line 417 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 420 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> CollectBy");
            
            #line 420 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 420 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CsType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 420 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 420 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 422 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 423 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".CollectBy");
            
            #line 423 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 423 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idName));
            
            #line default
            #line hidden
            this.Write(", dc)).Select(o=> new ");
            
            #line 423 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 425 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

	foreach (var method in table.Collects)
	{
		if (method.Fields.Count == 0)
			continue;
		var name = method.NameByParameters("Collect");
		if (collected.Contains(name))
			continue;
		collected.Add(name);

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic static IEnumerable<");
            
            #line 438 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 438 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 438 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeDeclaration()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 438 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 440 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn ");
            
            #line 441 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 441 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 441 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeParameters()));
            
            #line default
            #line hidden
            this.Write(", dc).Select(o=> new ");
            
            #line 441 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n\r\n\t\tpublic static async Task<IEnumerable<");
            
            #line 444 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 444 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 444 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeDeclaration()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 444 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dcDeclare));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tAssertion.Ensures(Assertion.Result<IEnumerable<");
            
            #line 446 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">>() != null);\r\n\t\t\treturn (await ");
            
            #line 447 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 447 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 447 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.MakeParameters()));
            
            #line default
            #line hidden
            this.Write(", dc)).Select(o=> new ");
            
            #line 447 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(o));\r\n\t\t}\r\n");
            
            #line 449 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\t#endregion\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Projects\kraftpro\Lexxys.T1\src\Lexxys.T1\Templates\ObjectTemplate.tt"

private global::Lexxys.T1.TableInfo _tableField;

/// <summary>
/// Access the table parameter of the template.
/// </summary>
private global::Lexxys.T1.TableInfo table
{
    get
    {
        return this._tableField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool tableValueAcquired = false;
if (this.Session.ContainsKey("table"))
{
    this._tableField = ((global::Lexxys.T1.TableInfo)(this.Session["table"]));
    tableValueAcquired = true;
}
if ((tableValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("table");
    if ((data != null))
    {
        this._tableField = ((global::Lexxys.T1.TableInfo)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ObjectTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
